Why  arch
Signed-off-by: TigerClips1 <spongebob1966@proton.me>

diff --git a/scripts/libmakepkg/executable/fakeroot.sh.in b/scripts/libmakepkg/executable/fakeroot.sh.in
--- a/scripts/libmakepkg/executable/fakeroot.sh.in
+++ b/scripts/libmakepkg/executable/fakeroot.sh.in
@@ -1,8 +1,8 @@
-#!/bin/bash
+#!/usr/bin/bash
 #
-#   @PROGNAME@ - a wrapper for running the real @PROGNAME@ in the source tree
+#   fakeroot.sh - Confirm presence of fakeroot binary
 #
-#   Copyright (c) 2013-2025 Pacman Development Team <pacman-dev@lists.archlinux.org>
+#   Copyright (c) 2011-2025 Pacman Development Team <pacman-dev@lists.archlinux.org>
 #
 #   This program is free software; you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
@@ -18,6 +18,20 @@
 #   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 
-DIR="@PWD@"
+[[ -n "$LIBMAKEPKG_EXECUTABLE_FAKEROOT_SH" ]] && return
+LIBMAKEPKG_EXECUTABLE_FAKEROOT_SH=1
 
-MAKEPKG_LIBRARY="$DIR"/libmakepkg exec bash -$- "$DIR"/.lib/@PROGNAME@ "$@"
+MAKEPKG_LIBRARY=${MAKEPKG_LIBRARY:-'@libmakepkgdir@'}
+
+source "$MAKEPKG_LIBRARY/util/message.sh"
+
+executable_functions+=('executable_fakeroot')
+
+executable_fakeroot() {
+	if (( SOURCEONLY || BUILDPKG )); then
+		if ! type -p fakeroot >/dev/null; then
+			error "$(gettext "Cannot find the %s binary.")" "fakeroot"
+			return 1
+		fi
+	fi
+}
diff --git a/scripts/libmakepkg/executable/gzip.sh.in b/scripts/libmakepkg/executable/gzip.sh.in
--- a/scripts/libmakepkg/executable/gzip.sh.in
+++ b/scripts/libmakepkg/executable/gzip.sh.in
@@ -1,8 +1,8 @@
-#!/bin/bash
+#!/usr/bin/bash
 #
-#   @PROGNAME@ - a wrapper for running the real @PROGNAME@ in the source tree
+#   gzip.sh - Confirm presence of gzip binary
 #
-#   Copyright (c) 2013-2025 Pacman Development Team <pacman-dev@lists.archlinux.org>
+#   Copyright (c) 2011-2025 Pacman Development Team <pacman-dev@lists.archlinux.org>
 #
 #   This program is free software; you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
@@ -18,6 +18,21 @@
 #   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 
-DIR="@PWD@"
+[[ -n "$LIBMAKEPKG_EXECUTABLE_GZIP_SH" ]] && return
+LIBMAKEPKG_EXECUTABLE_GZIP_SH=1
 
-MAKEPKG_LIBRARY="$DIR"/libmakepkg exec bash -$- "$DIR"/.lib/@PROGNAME@ "$@"
+MAKEPKG_LIBRARY=${MAKEPKG_LIBRARY:-'@libmakepkgdir@'}
+
+source "$MAKEPKG_LIBRARY/util/message.sh"
+source "$MAKEPKG_LIBRARY/util/option.sh"
+
+executable_functions+=('executable_gzip')
+
+executable_gzip() {
+	if check_option "zipman" "y"; then
+		if ! type -p gzip >/dev/null; then
+			error "$(gettext "Cannot find the %s binary required for compressing man and info pages.")" "gzip"
+			return 1
+		fi
+	fi
+}
diff --git a/scripts/ps4mkpkg.sh.in b/scripts/ps4mkpkg.sh.in
--- a/scripts/ps4mkpkg.sh.in
+++ b/scripts/ps4mkpkg.sh.in
@@ -1,8 +1,8 @@
 #!/bin/bash
 #
-#   PS4MKPKG - make packages compatible for use with ps4
+#   makepkg - make packages compatible for use with pacman
 #
-#   Copyright (c) 2006-2025 ps4 Development Team <ps4-dev@lists.archlinux.org>
+#   Copyright (c) 2006-2025 Pacman Development Team <pacman-dev@lists.archlinux.org>
 #   Copyright (c) 2002-2006 by Judd Vinet <jvinet@zeroflux.org>
 #   Copyright (c) 2005 by Aurelien Foret <orelien@chez.com>
 #   Copyright (c) 2006 by Miklos Vajna <vmiklos@frugalware.org>
@@ -24,13 +24,13 @@
 #   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 
-# PS4MKPKG uses quite a few external programs during its execution. You
-# need to have at least the following installed for PS4MKPKG to function:
+# makepkg uses quite a few external programs during its execution. You
+# need to have at least the following installed for makepkg to function:
 #   awk, bsdtar (libarchive), bzip2, coreutils, fakeroot, file, find (findutils),
 #   gettext, gpg, grep, gzip, sed, tput (ncurses), xz
 
 # gettext initialization
-export TEXTDOMAIN='ps4-scripts'
+export TEXTDOMAIN='pacman-scripts'
 export TEXTDOMAINDIR='@localedir@'
 
 # file -i does not work on Mac OSX unless legacy mode is set
@@ -40,11 +40,11 @@ unset CDPATH
 # Ensure GREP_OPTIONS doesn't screw with our grep calls
 unset GREP_OPTIONS
 
-declare -r PS4MKPKG_version='@PACKAGE_VERSION@'
+declare -r makepkg_version='@PACKAGE_VERSION@'
 declare -r confdir='@sysconfdir@'
 declare -r BUILDSCRIPT='@BUILDSCRIPT@'
 
-PS4MKPKG_LIBRARY=${PS4MKPKG_LIBRARY:-'@libps4mkpkgdir@'}
+MAKEPKG_LIBRARY=${MAKEPKG_LIBRARY:-'@libmakepkgdir@'}
 
 # Options
 ASDEPS=0
@@ -80,16 +80,16 @@ SPLITPKG=0
 SOURCEONLY=0
 VERIFYSOURCE=0
 
-PS4MKPKG_LINT_PS4PKGBUILD=${PS4MKPKG_LINT_PS4PKGBUILD:-1}
+MAKEPKG_LINT_PKGBUILD=${MAKEPKG_LINT_PKGBUILD:-1}
 
-PS4_OPTS=()
+PACMAN_OPTS=()
 
 shopt -s extglob
 
 ### SUBROUTINES ###
 
-# Import libPS4MKPKG
-for lib in "$PS4MKPKG_LIBRARY"/*.sh; do
+# Import libmakepkg
+for lib in "$MAKEPKG_LIBRARY"/*.sh; do
 	source "$lib"
 done
 
@@ -186,7 +186,7 @@ enter_fakeroot() {
 }
 
 # Automatically update pkgver variable if a pkgver() function is provided
-# Re-sources the PS4PKGBUILD afterwards to allow for other variables that use $pkgver
+# Re-sources the PKGBUILD afterwards to allow for other variables that use $pkgver
 update_pkgver() {
 	msg "$(gettext "Starting %s()...")" "pkgver"
 	newpkgver=$(run_function_safe pkgver)
@@ -195,7 +195,7 @@ update_pkgver() {
 	fi
 	if ! check_pkgver "$newpkgver"; then
 		error "$(gettext "pkgver() generated an invalid version: %s")" "$newpkgver"
-		exit $E_PS4PKGBUILD_ERROR
+		exit $E_PKGBUILD_ERROR
 	fi
 
 	if [[ -n $newpkgver && $newpkgver != "$pkgver" ]]; then
@@ -206,7 +206,7 @@ update_pkgver() {
 			if ! printf '%s\n' "${buildfile[@]}" > "$BUILDFILE"; then
 				error "$(gettext "Failed to update %s from %s to %s")" \
 						"pkgver" "$pkgver" "$newpkgver"
-				exit $E_PS4PKGBUILD_ERROR
+				exit $E_PKGBUILD_ERROR
 			fi
 			source_safe "$BUILDFILE"
 			local fullver=$(get_full_version)
@@ -218,35 +218,35 @@ update_pkgver() {
 	fi
 }
 
-# Print 'source not found' error message and exit PS4MKPKG
+# Print 'source not found' error message and exit makepkg
 missing_source_file() {
 	error "$(gettext "Unable to find source file %s.")" "$(get_filename "$1")"
 	plainerr "$(gettext "Aborting...")"
 	exit $E_MISSING_FILE
 }
 
-run_ps4() {
+run_pacman() {
 	local cmd cmdescape
 	if [[ $1 = -@(T|Q)*([[:alpha:]]) ]]; then
-		cmd=("$PS4_PATH" "$@")
+		cmd=("$PACMAN_PATH" "$@")
 	else
-		cmd=("$PS4_PATH" "${PS4_OPTS[@]}" "$@")
+		cmd=("$PACMAN_PATH" "${PACMAN_OPTS[@]}" "$@")
 		cmdescape="$(printf '%q ' "${cmd[@]}")"
-		if (( ${#PS4_AUTH[@]} )); then
-			if in_array '%c' "${PS4_AUTH[@]}"; then
-				cmd=("${PS4_AUTH[@]/\%c/$cmdescape}")
+		if (( ${#PACMAN_AUTH[@]} )); then
+			if in_array '%c' "${PACMAN_AUTH[@]}"; then
+				cmd=("${PACMAN_AUTH[@]/\%c/$cmdescape}")
 			else
-				cmd=("${PS4_AUTH[@]}" "${cmd[@]}")
+				cmd=("${PACMAN_AUTH[@]}" "${cmd[@]}")
 			fi
 		elif type -p sudo >/dev/null; then
 			cmd=(sudo -k "${cmd[@]}")
 		else
 			cmd=(su root -c "$cmdescape")
 		fi
-		local lockfile="$(ps4-conf DBPath)/ps4db.lock"
+		local lockfile="$(pacman-conf DBPath)/db.lck"
 		while [[ -f $lockfile ]]; do
 			local timer=0
-			msg "$(gettext "Ps4 is currently in use, please wait...")"
+			msg "$(gettext "Pacman is currently in use, please wait...")"
 			while [[ -f $lockfile ]] && (( timer < 10 )); do
 				(( ++timer ))
 				sleep 3
@@ -261,13 +261,13 @@ check_deps() {
 
 	local ret=0
 	local pmout
-	pmout=$(run_ps4 -T "$@")
+	pmout=$(run_pacman -T "$@")
 	ret=$?
 
 	if (( ret == 127 )); then #unresolved deps
 		printf "%s\n" "$pmout"
 	elif (( ret )); then
-		error "$(gettext "'%s' returned a fatal error (%i): %s")" "$PS4" "$ret" "$pmout"
+		error "$(gettext "'%s' returned a fatal error (%i): %s")" "$PACMAN" "$ret" "$pmout"
 		return "$ret"
 	fi
 }
@@ -285,11 +285,11 @@ handle_deps() {
 	fi
 
 	if (( DEP_BIN )); then
-		# install missing deps from binary packages (using ps4 -S)
+		# install missing deps from binary packages (using pacman -S)
 		msg "$(gettext "Installing missing dependencies...")"
 
-		if ! run_ps4 -S --asdeps "${deplist[@]}"; then
-			error "$(gettext "'%s' failed to install missing dependencies.")" "$PS4"
+		if ! run_pacman -S --asdeps "${deplist[@]}"; then
+			error "$(gettext "'%s' failed to install missing dependencies.")" "$PACMAN"
 			return $R_DEPS_MISSING
 		fi
 	fi
@@ -353,7 +353,7 @@ remove_deps() {
 
 	msg "Removing installed dependencies..."
 	# exit cleanly on failure to remove deps as package has been built successfully
-	if ! run_ps4 -Rnu ${deplist[@]}; then
+	if ! run_pacman -Rnu ${deplist[@]}; then
 		warning "$(gettext "Failed to remove installed dependencies.")"
 		return $E_REMOVE_DEPS_FAILED
 	fi
@@ -476,7 +476,7 @@ write_kv_pair() {
 	for val in "$@"; do
 		if [[ $val = *$'\n'* ]]; then
 			error "$(gettext "Invalid value for %s: %s")" "$key" "$val"
-			exit $E_PS4PKGBUILD_ERROR
+			exit $E_PKGBUILD_ERROR
 		fi
 		printf "%s = %s\n" "$key" "$val"
 	done
@@ -488,7 +488,7 @@ write_pkginfo() {
 	merge_arch_attrs
 	generate_autodeps
 
-	printf "# Generated by PS4MKPKG %s\n" "$PS4MKPKG_version"
+	printf "# Generated by makepkg %s\n" "$makepkg_version"
 	printf "# using %s\n" "$(fakeroot -v)"
 
 	write_kv_pair "pkgname" "$pkgname"
@@ -535,18 +535,18 @@ write_buildinfo() {
 
 	local sum="$(sha256sum "${BUILDFILE}")"
 	sum=${sum%% *}
-	write_kv_pair "PS4pkgbuild_sha256sum" $sum
+	write_kv_pair "pkgbuild_sha256sum" $sum
 
 	write_kv_pair "packager" "${PACKAGER}"
 	write_kv_pair "builddate" "${SOURCE_DATE_EPOCH}"
 	write_kv_pair "builddir"  "${BUILDDIR}"
 	write_kv_pair "startdir"  "${startdir}"
-	write_kv_pair "buildtool" "${BUILDTOOL:-PS4MKPKG}"
-	write_kv_pair "buildtoolver" "${BUILDTOOLVER:-$PS4MKPKG_version}"
+	write_kv_pair "buildtool" "${BUILDTOOL:-makepkg}"
+	write_kv_pair "buildtoolver" "${BUILDTOOLVER:-$makepkg_version}"
 	write_kv_pair "buildenv" "${BUILDENV[@]}"
 	write_kv_pair "options" "${OPTIONS[@]}"
 
-	local pkginfos_parsed=($(LC_ALL=C run_ps4 -Qi | awk -F': ' '\
+	local pkginfos_parsed=($(LC_ALL=C run_pacman -Qi | awk -F': ' '\
 		/^Name .*/ {printf "%s", $2} \
 		/^Version .*/ {printf "-%s", $2} \
 		/^Architecture .*/ {print "-"$2} \
@@ -751,9 +751,9 @@ install_package() {
 	RMDEPS=0
 
 	if (( ! SPLITPKG )); then
-		msg "$(gettext "Installing package %s with %s...")" "$pkgname" "$ps4 -U"
+		msg "$(gettext "Installing package %s with %s...")" "$pkgname" "$PACMAN -U"
 	else
-		msg "$(gettext "Installing %s package group with %s...")" "$pkgbase" "$ps4 -U"
+		msg "$(gettext "Installing %s package group with %s...")" "$pkgbase" "$PACMAN -U"
 	fi
 
 	local fullver pkgarch pkg pkglist
@@ -770,7 +770,7 @@ install_package() {
 		fi
 	done
 
-	if ! run_ps4 -U "${pkglist[@]}"; then
+	if ! run_pacman -U "${pkglist[@]}"; then
 		warning "$(gettext "Failed to install built package(s).")"
 		return $E_INSTALL_FAILED
 	fi
@@ -868,9 +868,9 @@ run_split_packaging() {
 }
 
 usage() {
-	printf "PS4MKPKG (ps4) %s\n" "$PS4MKPKG_version"
+	printf "makepkg (pacman) %s\n" "$makepkg_version"
 	echo
-	printf -- "$(gettext "Make packages compatible for use with ps4")\n"
+	printf -- "$(gettext "Make packages compatible for use with pacman")\n"
 	echo
 	printf -- "$(gettext "Usage: %s [options]")\n" "$0"
 	echo
@@ -879,7 +879,7 @@ usage() {
 	printf -- "$(gettext "  -c, --clean      Clean up work files after build")\n"
 	printf -- "$(gettext "  -C, --cleanbuild Remove %s dir before building the package")\n" "\$srcdir/"
 	printf -- "$(gettext "  -d, --nodeps     Skip all dependency checks")\n"
-	printf -- "$(gettext "  -D, --dir <dir>  Change to directory <dir> before processing PS4PKGBUILD")\n"
+	printf -- "$(gettext "  -D, --dir <dir>  Change to directory <dir> before processing PKGBUILD")\n"
 	printf -- "$(gettext "  -e, --noextract  Do not extract source files (use existing %s dir)")\n" "\$srcdir/"
 	printf -- "$(gettext "  -f, --force      Overwrite existing package")\n"
 	printf -- "$(gettext "  -g, --geninteg   Generate integrity checks for source files")\n"
@@ -891,12 +891,12 @@ usage() {
 	printf -- "$(gettext "  -p <file>        Use an alternate build script (instead of '%s')")\n" "$BUILDSCRIPT"
 	printf -- "$(gettext "  -r, --rmdeps     Remove installed dependencies after a successful build")\n"
 	printf -- "$(gettext "  -R, --repackage  Repackage contents of the package without rebuilding")\n"
-	printf -- "$(gettext "  -s, --syncdeps   Install missing dependencies with %s")\n" "ps4"
+	printf -- "$(gettext "  -s, --syncdeps   Install missing dependencies with %s")\n" "pacman"
 	printf -- "$(gettext "  -S, --source     Generate a source-only tarball without downloaded sources")\n"
 	printf -- "$(gettext "  -V, --version    Show version information and exit")\n"
 	printf -- "$(gettext "  --allsource      Generate a source-only tarball including downloaded sources")\n"
 	printf -- "$(gettext "  --check          Run the %s function in the %s")\n" "check()" "$BUILDSCRIPT"
-	printf -- "$(gettext "  --config <file>  Use an alternate config file (instead of '%s')")\n" "$confdir/PS4MKPKG.conf"
+	printf -- "$(gettext "  --config <file>  Use an alternate config file (instead of '%s')")\n" "$confdir/makepkg.conf"
 	printf -- "$(gettext "  --holdver        Do not update VCS sources")\n"
 	printf -- "$(gettext "  --key <key>      Specify a key to use for %s signing instead of the default")\n" "gpg"
 	printf -- "$(gettext "  --noarchive      Do not create package archive")\n"
@@ -911,20 +911,20 @@ usage() {
 	printf -- "$(gettext "  --skippgpcheck   Do not verify source files with PGP signatures")\n"
 	printf -- "$(gettext "  --verifysource   Download source files (if needed) and perform integrity checks")\n"
 	echo
-	printf -- "$(gettext "These options can be passed to %s:")\n" "ps4"
+	printf -- "$(gettext "These options can be passed to %s:")\n" "pacman"
 	echo
 	printf -- "$(gettext "  --asdeps         Install packages as non-explicitly installed")\n"
 	printf -- "$(gettext "  --needed         Do not reinstall the targets that are already up to date")\n"
 	printf -- "$(gettext "  --noconfirm      Do not ask for confirmation when resolving dependencies")\n"
 	printf -- "$(gettext "  --noprogressbar  Do not show a progress bar when downloading files")\n"
 	echo
-	printf -- "$(gettext "If %s is not specified, %s will look for '%s'")\n" "-p" "PS4MKPKG" "$BUILDSCRIPT"
+	printf -- "$(gettext "If %s is not specified, %s will look for '%s'")\n" "-p" "makepkg" "$BUILDSCRIPT"
 	echo
 }
 
 version() {
-	printf "PS4MKPKG (ps4) %s\n" "$PS4MKPKG_version"
-	printf -- "Copyright (c) 2006-2025 ps4 Development Team <ps4-dev@lists.archlinux.org>.\n"
+	printf "makepkg (pacman) %s\n" "$makepkg_version"
+	printf -- "Copyright (c) 2006-2025 Pacman Development Team <pacman-dev@lists.archlinux.org>.\n"
 	printf -- "Copyright (C) 2002-2006 Judd Vinet <jvinet@zeroflux.org>.\n"
 	printf '\n'
 	printf -- "$(gettext "\
@@ -954,7 +954,7 @@ OPT_LONG=('allsource' 'check' 'clean' 'cleanbuild' 'config:' 'dir:' 'force' 'gen
           'printsrcinfo' 'repackage' 'rmdeps' 'sign' 'skipchecksums' 'skipinteg'
           'skippgpcheck' 'source' 'syncdeps' 'verifysource' 'version')
 
-# ps4 Options
+# Pacman Options
 OPT_LONG+=('asdeps' 'noconfirm' 'needed' 'noprogressbar')
 
 if ! parseopts "$OPT_SHORT" "${OPT_LONG[@]}" -- "$@"; then
@@ -965,19 +965,19 @@ unset OPT_SHORT OPT_LONG OPTRET
 
 while true; do
 	case "$1" in
-		# ps4 Options
+		# Pacman Options
 		--asdeps)         ASDEPS=1;;
 		--needed)         NEEDED=1;;
-		--noconfirm)      PS4_OPTS+=("--noconfirm") ;;
-		--noprogressbar)  PS4_OPTS+=("--noprogressbar") ;;
+		--noconfirm)      PACMAN_OPTS+=("--noconfirm") ;;
+		--noprogressbar)  PACMAN_OPTS+=("--noprogressbar") ;;
 
-		# PS4MKPKG Options
+		# Makepkg Options
 		--allsource)      BUILDPKG=0 SOURCEONLY=2 ;;
 		-A|--ignorearch)  IGNOREARCH=1 ;;
 		-c|--clean)       CLEANUP=1 ;;
 		-C|--cleanbuild)  CLEANBUILD=1 ;;
 		--check)          RUN_CHECK='y' ;;
-		--config)         shift; PS4MKPKG_CONF=$1 ;;
+		--config)         shift; MAKEPKG_CONF=$1 ;;
 		-d|--nodeps)      NODEPS=1 ;;
 		-D|--dir)         shift; CHDIR=$1 ;;
 		-e|--noextract)   NOEXTRACT=1 ;;
@@ -989,7 +989,7 @@ while true; do
 		-i|--install)     INSTALL=1 ;;
 		--key)            shift; GPGKEY=$1 ;;
 		-L|--log)         LOGGING=1 ;;
-		-m|--nocolor)     USE_COLOR='n'; PS4_OPTS+=("--color" "never") ;;
+		-m|--nocolor)     USE_COLOR='n'; PACMAN_OPTS+=("--color" "never") ;;
 		--noarchive)      NOARCHIVE=1 ;;
 		--nocheck)        RUN_CHECK='n' ;;
 		--noverify)       RUN_VERIFY='n' ;;
@@ -1041,7 +1041,7 @@ done
 trap 'trap_exit INT "$(gettext "Aborted by user! Exiting...")"' INT
 trap 'trap_exit USR1 "$(gettext "An unknown error has occurred. Exiting...")"' ERR
 
-load_ps4mkpkg_config
+load_makepkg_config
 
 # override settings from extra variables on commandline, if any
 if (( ${#extra_environment[*]} )); then
@@ -1055,10 +1055,10 @@ done
 unset var
 PACKAGER=${PACKAGER:-"Unknown Packager"}
 
-# set ps4 command if not already defined
-PS4=${PS4:-ps4}
+# set pacman command if not already defined
+PACMAN=${PACMAN:-pacman}
 # save full path to command as PATH may change when sourcing /etc/profile
-PS4_PATH=$(type -P $PS4)
+PACMAN_PATH=$(type -P $PACMAN)
 
 # check if messages are to be printed using color
 if [[ -t 2 && $USE_COLOR != "n" ]] && check_buildenv "color" "y"; then
@@ -1068,7 +1068,7 @@ else
 fi
 
 
-# check PS4MKPKG.conf for some basic requirements
+# check makepkg.conf for some basic requirements
 lint_config || exit $E_CONFIG_ERROR
 
 
@@ -1107,12 +1107,12 @@ fi
 if (( ! INFAKEROOT )); then
 	if (( EUID == 0 )); then
 		error "$(gettext "Running %s as root is not allowed as it can cause permanent,\n\
-catastrophic damage to your system.")" "PS4MKPKG"
+catastrophic damage to your system.")" "makepkg"
 		exit $E_ROOT
 	fi
 else
 	if [[ -z $FAKEROOTKEY ]]; then
-		error "$(gettext "Do not use the %s option. This option is only for internal use by %s.")" "'-F'" "PS4MKPKG"
+		error "$(gettext "Do not use the %s option. This option is only for internal use by %s.")" "'-F'" "makepkg"
 		exit $E_INVALID_OPTION
 	fi
 fi
@@ -1128,17 +1128,17 @@ unset "${!sha256sums_@}" "${!sha384sums_@}" "${!sha512sums_@}" "${!b2sums_@}"
 BUILDFILE=${BUILDFILE:-$BUILDSCRIPT}
 if [[ ! -f $BUILDFILE ]]; then
 	error "$(gettext "%s does not exist.")" "$BUILDFILE"
-	exit $E_PS4PKGBUILD_ERROR
+	exit $E_PKGBUILD_ERROR
 
 else
 	if [[ $(<"$BUILDFILE") = *$'\r'* ]]; then
 		error "$(gettext "%s contains %s characters and cannot be sourced.")" "$BUILDFILE" "CRLF"
-		exit $E_PS4PKGBUILD_ERROR
+		exit $E_PKGBUILD_ERROR
 	fi
 
 	if [[ ! $BUILDFILE -ef $PWD/${BUILDFILE##*/} ]]; then
 		error "$(gettext "%s must be in the current working directory.")" "$BUILDFILE"
-		exit $E_PS4PKGBUILD_ERROR
+		exit $E_PKGBUILD_ERROR
 	fi
 
 	if [[ ${BUILDFILE:0:1} != "/" ]]; then
@@ -1149,9 +1149,9 @@ fi
 
 pkgbase=${pkgbase:-${pkgname[0]}}
 
-# check the PS4PKGBUILD for some basic requirements
-if (( PS4MKPKG_LINT_PS4PKGBUILD != 0 )); then
-	lint_pkgbuild || exit $E_PS4PKGBUILD_ERROR
+# check the PKGBUILD for some basic requirements
+if (( MAKEPKG_LINT_PKGBUILD != 0 )); then
+	lint_pkgbuild || exit $E_PKGBUILD_ERROR
 fi
 
 if (( !SOURCEONLY && !PRINTSRCINFO )); then
@@ -1189,7 +1189,7 @@ if (( ${#pkgname[@]} > 1 )) || have_function package_${pkgname}; then
 	SPLITPKG=1
 fi
 
-# test for available PS4PKGBUILD functions
+# test for available PKGBUILD functions
 if have_function verify; then
 	# "Hide" verify() function if not going to be run
 	if [[ $RUN_VERIFY != "n" ]] && (( ! SKIPCHECKSUMS && ! SKIPPGPCHECK )); then
@@ -1252,8 +1252,8 @@ if (( INFAKEROOT )); then
 	exit $E_OK
 fi
 
-# check we have the software required to process the PS4PKGBUILD
-check_software || exit $E_MISSING_PS4MKPKG_DEPS
+# check we have the software required to process the PKGBUILD
+check_software || exit $E_MISSING_MAKEPKG_DEPS
 
 # check if gpg signature is to be created and if signing key is valid
 if { [[ -z $SIGNPKG ]] && check_buildenv "sign" "y"; } || [[ $SIGNPKG == 'y' ]]; then
@@ -1308,7 +1308,7 @@ if (( NODEPS || ( VERIFYSOURCE && !DEP_BIN ) )); then
 	fi
 else
 	if (( RMDEPS && ! INSTALL )); then
-		original_pkglist=($(run_ps4 -Qq))    # required by remove_dep
+		original_pkglist=($(run_pacman -Qq))    # required by remove_dep
 	fi
 	deperr=0
 
@@ -1316,7 +1316,7 @@ else
 	resolve_deps ${depends[@]} || deperr=1
 
 	if (( RMDEPS && INSTALL )); then
-		original_pkglist=($(run_ps4 -Qq))    # required by remove_dep
+		original_pkglist=($(run_pacman -Qq))    # required by remove_dep
 	fi
 
 	if (( ! deperr )); then
@@ -1329,7 +1329,7 @@ else
 	fi
 
 	if (( RMDEPS )); then
-		current_pkglist=($(run_ps4 -Qq))    # required by remove_deps
+		current_pkglist=($(run_pacman -Qq))    # required by remove_deps
 	fi
 
 	if (( deperr )); then
